server:
    port: 8888

spring:
    application:
        name: mcsv-config-server
    cloud:
        config:
            discovery:
                enabled: true
                #serviceId: config-service
                #service-id:  mcsv-config-server
                service-id: mcsv-config-server 
            
            server:
                git:
                    # uri: https://github.com/SIAT-MPM/configuracion_servicios.git
                    uri: https://github.com/MYCLOUD2-DEVELOPER/file_config.git
                    
                    username: 'crojasadicse'

                    password: ${{MY_SECRET}}

                    clone-on-start: true

                # la rama de git
                default-label: master
            
eureka:
    instance:
        instanceId: ${spring.application.name}:${server.port}
        lease-expiration-duration-in-seconds: 30
    client:
        serviceUrl:
            defaultZone:  ${EUREKA_SERVER:http://localhost:8761/eureka}
            registerWithEureka: true
            fetchRegistry: true
            healthcheck:
               enabled: true
            refresh:
               enable: true 


