server:
    port: 8888

spring:
    application:
        name: mcsv-config-server
    cloud:
        config:
            discovery:
                enabled: true
                #serviceId: config-service
                #service-id:  mcsv-config-server
                service-id: mcsv-config-server 
            
            server:
         
                default-label: master
            
eureka:
    instance:
        instanceId: ${spring.application.name}:${server.port}
        lease-expiration-duration-in-seconds: 30
    client:
        serviceUrl:
            defaultZone:  ${EUREKA_SERVER:http://localhost:8761/eureka}
            registerWithEureka: true
            fetchRegistry: true
            healthcheck:
               enabled: true
            refresh:
               enable: true 


